### ISSUE TITLE
Why is this here?

### ISSUE THREAD

**Issue by yCobanoglu** [ElectronicBabylonianLiterature/ebl-frontend#18]
Why is this here?

_Originally posted by @jlaasonen in https://github.com/ElectronicBabylonianLiterature/ebl-frontend/pull/17_

Depending on the rulingNumber the corresponding number of divs are displayed so 1 div for one and, ... , and 3 for three rulings. The number is turned into an Array like [0,1,2] for three and iterated over with .map and a div is added each time.

**Comment by jlaasonen** [comment]
#17 is about the line numbers. Why are there changes to rulings?

**Comment by yCobanoglu** [comment]
I checked out the format_display_number branch from our old rulings branch unfortunately.

**Comment by jlaasonen** [comment]
If the new feature branch is not created from master it is best to create a new clean branch any cherry-pick possible commits.

Is it easy to get rid of the rulings code? Since we squash merge having the wrong branch as a parent should not cause problems. A normal merge would result in a confusing history.

**Comment by yCobanoglu** [comment]
Ok yeah it is easy to get rid of the rulings.
